### ISSUE TITLE
Exception in thread "AWT-EventQueue-0"

### ISSUE THREAD

**Issue by cxdy** [FreakHaxme/Game-tracker#3]
Created my mob and added HP successfully, but upon adding the `initiative` my console outputs the following error.

```
Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: "Kill the pussy"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:658)
	at java.base/java.lang.Integer.parseInt(Integer.java:776)
	at GUI$EventHandler.actionPerformed(GUI.java:85)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

GUI doesn't update with new mob info, guessing that's due to this error though.
Looks great on Mac OS though!

<img width="511" alt="Screenshot 2019-04-28 03 52 09" src="https://user-images.githubusercontent.com/6620597/56860868-1e290c80-6969-11e9-8b6a-a4de0a83a02e.png">

If this isn't an error you guys have experienced before, here's how I did everything. To paint a picture for you, I have only written a Hello World program in Java, so I know nothing about this language.

First, I ran `brew cask install java` - this installs JDK and JRE, so I can compile and run Java files.
Then, I ran `javac Main.java` - this is the compile command (not entirely sure if I compiled the right one, however it did make classes for each file so I think that's correct)
Then to run the program, I just did `java Main.java` - GUI opened, added the mob name and HP (with no error), but got an error when doing the initiative. I receive an error for initiative regardless of if the string contains spaces (if that matters, just thought I'd try it.)

**Comment by cxdy** [comment]
I know this isn't a big project or anything, just thought I'd make an issue cause I appreciate it when people test my stuff :)

**Comment by martintc** [comment]
Looks like the code is expecting to a number that it takes in as a String, then tries to parse an integer out of it. This shouldn't throw an error if a number is entered. We could do some better error handlng, so instead of causing an issue, if the user inputs a string, a dialog window will pop up with a warning.

**Comment by martintc** [comment]
@FreakHaxme If you don't have time to correct this, you can assign me to it and I can write something up to fix this.

**Comment by FreakHaxme** [comment]
Thank you @cxdy for the issue!
As @martintc said, the issue is because you're supposed to enter a number instead of a string there, but I've taken the opportunity to add all of the necessary exception handling regardless. The program should now check all values to see if they're acceptable even in other areas that you didn't mention.
